image: tiangolo/docker-with-compose:latest
pipelines:
  default:
    - parallel:
      - step:
        name: PHP 7.2
        caches:
          - docker
          - composer
          - pip
        services:
          - docker
        script:
          - apk add --no-cache bash rsync
          - rsync -avg ~/.composer/ ./build/composer/
          - chmod -R 777 $BITBUCKET_CLONE_DIR
          - docker-compose -v
          - export PRIV_KEY=$MY_SSH_KEY
          - export PHP_VERSION=7.2
          - docker-compose up --abort-on-container-exit --exit-code-from test test
          - docker-compose down
          - rsync -avg ./build/composer/ ~/.composer/
      - step:
        name: PHP 7.1
        caches:
          - docker
          - composer
          - pip
        services:
          - docker
        script:
          - apk add --no-cache bash rsync
          - rsync -avg ~/.composer/ ./build/composer/
          - chmod -R 777 $BITBUCKET_CLONE_DIR
          - docker-compose -v
          - export PRIV_KEY=$MY_SSH_KEY
          - export PHP_VERSION=7.1
          - docker-compose up --abort-on-container-exit --exit-code-from test test
          - docker-compose down
          - rsync -avg ./build/composer/ ~/.composer/
