version: "3"
services:
  mysql:
    image: centos/mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=app
  app:
    image: qoboltd/docker-centos-nginx:${PHP_VERSION-latest}
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_NO_INTERACTION=1
      - COMPOSER_HOME=./build/composer
    volumes:
      - ./:/var/www/html
    ports:
      - 8000:8000
    user: ${FIXUID-1000}:${FIXGID-1000}
    entrypoint: >
      bash -c "set -x
      && echo 'waiting for mysql to start'
      && sh -c 'until printf \"\" 2>>/dev/null >> /dev/tcp/mysql/3306; do sleep 1; done'
      && echo 'mysql is up'
      && cd /var/www/html
      && mysql -h mysql -u root -proot -e 'drop database if exists app'
      && /usr/bin/fixuid
      && ./bin/composer validate
      && ./bin/composer install --no-progress --no-suggest
      && ./bin/build app:install CHOWN_USER=nginx,CHGRP_GROUP=nginx,DB_HOST=mysql,DB_NAME=app,DB_ADMIN_USER=root,DB_ADMIN_PASS=root,DB_USER=root,DB_PASS=root
      && echo 'Firing up PHP+Nginx, please proceed to http://localhost:8000'
      && php-fpm -D
      && nginx -g 'daemon off;'"
    depends_on:
      - mysql
  test:
    image: qoboltd/docker-centos-php:${PHP_VERSION-latest}
    environment:
      - COMPOSER_ALLOW_SUPERUSER=1
      - COMPOSER_NO_INTERACTION=1
      - COMPOSER_HOME=./build/composer
    volumes:
      - ./:/code
    entrypoint: >
      bash -c "set -x
      && echo 'waiting for mysql to start'
      && sh -c 'until printf \"\" 2>>/dev/null >> /dev/tcp/mysql/3306; do sleep 1; done'
      && echo 'mysql is up'
      && mysql -h mysql -u root -proot -e 'drop database if exists app'
      && echo 'Check PHP Version'
      && php --version
      && echo $PRIV_KEY | base64 -d -i > ~/.ssh/id_rsa
      && chmod -R u+rwX,go-rwX ~/.ssh
      && cd /code
      && ./bin/composer validate
      && ./bin/composer install --no-progress --no-suggest
      && ./vendor/bin/phpcs
      && ./bin/build app:install CHOWN_USER=root,CHGRP_GROUP=root,DB_HOST=mysql,DB_NAME=app,DB_ADMIN_USER=root,DB_ADMIN_PASS=root,DB_USER=root,DB_PASS=root
      && ./vendor/bin/phpunit --group example --no-coverage
      && ./vendor/bin/phpunit --exclude-group example,external --no-coverage"
    depends_on:
      - mysql
